#+Title: JOM299
#+Author: Basile Simon
#+Email: basile.simon@city.ac.uk

* week 1: the basics
We'll talk at length about the module itself and how it will be evaluated. We'll look at some online resources to look at every week to get a feel for what's going on in the field of interactive journalism. We will also go through a general introduction to programming concepts - which are applicable regardless of the programming language you choose.
* week 2: air pollution on Euston Road
We will work our way through a dataset of air pollution in London and produce a simple visualisation. This will give us the chance to clean and tidy up a dataset (a prerequisite to much of the work we do) and enrich it with average calculations.
* week 3: LGBTI index in Europe
We will represent a dataset as a map of Europe and talk through geographical projections and colour theory to illustrate the state of LGBT rights on the continent.
* week 4: wrangling GE2019 data
We will push our mapping skills a little further and model some of the results from the December general election, as we would on an election results day, producing incresingly interesting visualisations supporting news lines as we go along.
* week 5: scraping crime data in London
We will understand how to automate the collection of police and crime data and design from the ground up a large-ish dataset.
* week 6: exploring crime data in London
From the aforementioned dataset of crime, we will move on to some exploratory data analysis, looking out for patterns and broad trends in our data.
* week 7: ???
* weeks 8, 9, 10: final project
We will go round the room and take questions about final project. Come prepared with actual problems, be happy to work collaboratively and to make progress in class while we tackle challenges collectively, on the big screen.
